# Generated by Django 4.2.2 on 2023-08-23 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('updated_by', models.CharField(auto_created=True, default='admin', max_length=250)),
                ('created_by', models.CharField(auto_created=True, default='admin', max_length=250)),
                ('id', models.CharField(default=uuid.UUID('a1eb8c1d-4cf3-458d-918d-2e4503580ccf'), max_length=200, primary_key=True, serialize=False, unique=True)),
                ('document_id', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
