# Generated by Django 4.2.2 on 2023-08-23 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.CharField(auto_created=True, default=uuid.UUID('c876e3ed-6eb6-4d10-973e-a9d1739aee1d'), max_length=250, primary_key=True, serialize=False),
        ),
    ]
